import Web3 from 'web3'

if(typeof web3 == 'undefined')
{
    console.log("No tenes Metamask Capo!")

}else{

    web3 = new Web3(window.ethereum || Web3.givenProvider);

    var contract = new web3.eth.Contract(
        [{"type":"event","name":"OwnershipTransferred","inputs":[{"type":"address","name":"previousOwner","internalType":"address","indexed":true},
{"type":"address","name":"newOwner","internalType":"address","indexed":true}],"anonymous":false},{"type":"event","name":"Transfer","inputs":[{"type":"address","name":"from","internalType":"address","indexed":true},{"type":"address","name":"to","internalType":"address","indexed":true},
{"type":"uint256","name":"tokenId","internalType":"uint256","indexed":true}],"anonymous":false},{"type":"event","name":"TransferData","inputs":[{"type":"bytes","name":"data","internalType":"bytes","indexed":false}],"anonymous":false},{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"_asks","inputs":[{"type":"uint256","name":"","internalType":"uint256"}]},
{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"_balances","inputs":[{"type":"address","name":"","internalType":"address"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"address","name":"bidder","internalType":"address payable"},{"type":"uint256","name":"amountInWEI","internalType":"uint256"},{"type":"uint256","name":"timestamp","internalType":"uint256"}],"name":"_bids","inputs":[{"type":"uint256","name":"","internalType":"uint256"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"address","name":"","internalType":"address"}],"name":"_owners","inputs":[{"type":"uint256","name":"","internalType":"uint256"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"uint32","name":"","internalType":"uint32"}],"name":"_tokenFeeLevels","inputs":[{"type":"uint256","name":"","internalType":"uint256"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"addArtwork","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"},{"type":"uint256","name":"num_original","internalType":"uint256"},
{"type":"uint256","name":"num_gold","internalType":"uint256"},{"type":"uint256","name":"num_silver","internalType":"uint256"},
{"type":"uint256","name":"num_bronze","internalType":"uint256"},{"type":"uint256","name":"price_silver","internalType":"uint256"},
{"type":"uint256","name":"price_bronze","internalType":"uint256"},{"type":"string","name":"propertyInfo","internalType":"string"},
{"type":"string","name":"propertyBronzeImage","internalType":"string"},{"type":"string","name":"propertyGoldImage","internalType":"string"},
{"type":"string","name":"propertySilverImage","internalType":"string"},{"type":"string","name":"propertyOriginalImage","internalType":"string"}]},
{"type":"function","stateMutability":"view","outputs":[{"type":"string","name":"","internalType":"string"}],"name":"artwork_names_list","inputs":[{"type":"uint256","name":"","internalType":"uint256"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"bool","name":"exists","internalType":"bool"},
{"type":"uint256","name":"num_original","internalType":"uint256"},{"type":"uint256","name":"num_gold","internalType":"uint256"},
{"type":"uint256","name":"num_silver","internalType":"uint256"},{"type":"uint256","name":"num_bronze","internalType":"uint256"},
{"type":"uint256","name":"price_silver","internalType":"uint256"},{"type":"uint256","name":"price_bronze","internalType":"uint256"},
{"type":"string","name":"propertyInfo","internalType":"string"},{"type":"string","name":"propertyBronzeImage","internalType":"string"},
{"type":"string","name":"propertyOriginalImage","internalType":"string"},{"type":"string","name":"propertySilverImage","internalType":"string"},{"type":"string","name":"propertyGoldImage","internalType":"string"}],"name":"artworks","inputs":[{"type":"string","name":"","internalType":"string"}]},
{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"artworks_count","inputs":[]},
{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"balanceOf","inputs":[{"type":"address","name":"owner","internalType":"address"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"bidLock","inputs":[]},{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"price","internalType":"uint256"},{"type":"address","name":"bidder","internalType":"address payable"},
{"type":"uint256","name":"timestamp","internalType":"uint256"}],"name":"bidOf","inputs":[{"type":"uint256","name":"_tokenId","internalType":"uint256"}]},{"type":"function","stateMutability":"payable","outputs":[],"name":"buyBronze","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"}]},
{"type":"function","stateMutability":"payable","outputs":[],"name":"buyGold","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"}]},
{"type":"function","stateMutability":"payable","outputs":[],"name":"buyOriginal","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"}]},
{"type":"function","stateMutability":"payable","outputs":[],"name":"buySilver","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"}]},
{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"changeDefaultAuctionDurtion","inputs":[{"type":"uint256","name":"_newDuration","internalType":"uint256"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"configureAuction","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"},
{"type":"uint256","name":"_goldMinPrice","internalType":"uint256"},{"type":"uint256","name":"_originalMinPrice","internalType":"uint256"},
{"type":"uint256","name":"_goldStartTimestamp","internalType":"uint256"},{"type":"uint256","name":"_originalStartTimestamp","internalType":"uint256"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"default_auction_duration","inputs":[]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"endGoldRound","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"endOriginalRound","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"}]},
{"type":"function","stateMutability":"view","outputs":[{"type":"address","name":"feeReceiver","internalType":"address payable"},{"type":"uint256","name":"feePercentage","internalType":"uint256"}],"name":"feeLevels","inputs":[{"type":"uint32","name":"","internalType":"uint32"}]},
{"type":"function","stateMutability":"view","outputs":[{"type":"tuple","name":"","internalType":"struct INFT.Properties","components":[{"type":"string[]","name":"properties","internalType":"string[]"}]}],"name":"getTokenProperties","inputs":[{"type":"uint256","name":"_tokenId","internalType":"uint256"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"address","name":"winner","internalType":"address"},{"type":"uint256","name":"bet","internalType":"uint256"},{"type":"uint256","name":"start_timestamp","internalType":"uint256"},{"type":"uint256","name":"duration","internalType":"uint256"},{"type":"uint256","name":"min_price","internalType":"uint256"}],"name":"gold_auctions","inputs":[{"type":"string","name":"","internalType":"string"}]},
{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"initialize","inputs":[{"type":"string","name":"name_","internalType":"string"},
{"type":"string","name":"symbol_","internalType":"string"},{"type":"uint256","name":"_defaultFee","internalType":"uint256"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"last_minted_id","inputs":[]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"mint","inputs":[{"type":"address","name":"_to","internalType":"address"},{"type":"uint256","name":"_tokenId","internalType":"uint256"},{"type":"string","name":"_tokenImage","internalType":"string"},{"type":"string","name":"_tokenArtist","internalType":"string"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"modifyArtworkInfo","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"},{"type":"string","name":"_newInfo","internalType":"string"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"string","name":"","internalType":"string"}],"name":"name","inputs":[]},{"type":"function","stateMutability":"view","outputs":[{"type":"address","name":"winner","internalType":"address"},{"type":"uint256","name":"bet","internalType":"uint256"},{"type":"uint256","name":"start_timestamp","internalType":"uint256"},{"type":"uint256","name":"duration","internalType":"uint256"},{"type":"uint256","name":"min_price","internalType":"uint256"}],"name":"original_auctions","inputs":[{"type":"string","name":"","internalType":"string"}]},{"type":"function","stateMutability":"view","outputs":[{"type":"address","name":"","internalType":"address"}],"name":"owner","inputs":[]},{"type":"function","stateMutability":"view","outputs":[{"type":"address","name":"","internalType":"address"}],"name":"ownerOf","inputs":[{"type":"uint256","name":"tokenId","internalType":"uint256"}]},
{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"priceOf","inputs":[{"type":"uint256","name":"_tokenId","internalType":"uint256"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"renounceOwnership",
"inputs":[]},{"type":"function","stateMutability":"view","outputs":[{"type":"uint256","name":"","internalType":"uint256"}],"name":"revenue","inputs":[]},
{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"rewardsWithdraw","inputs":[]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"safeTransferFrom","inputs":[{"type":"address","name":"from","internalType":"address"},{"type":"address","name":"to","internalType":"address"},{"type":"uint256","name":"tokenId","internalType":"uint256"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"safeTransferFrom","inputs":[{"type":"address","name":"from","internalType":"address"},{"type":"address","name":"to","internalType":"address"},{"type":"uint256","name":"tokenId","internalType":"uint256"},{"type":"bytes","name":"_data","internalType":"bytes"}]},{"type":"function","stateMutability":"payable","outputs":[],"name":"setBid","inputs":[{"type":"uint256","name":"_tokenId","internalType":"uint256"},{"type":"bytes","name":"_data","internalType":"bytes"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"setFeeReceiver","inputs":[{"type":"address","name":"_address","internalType":"address"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"setPrice","inputs":[{"type":"uint256","name":"_tokenId","internalType":"uint256"},{"type":"uint256","name":"_amountInWEI","internalType":"uint256"}]},{"type":"function","stateMutability":"nonpayable","outputs":[{"type":"bool","name":"","internalType":"bool"}],"name":"silentTransfer","inputs":[{"type":"address","name":"_to","internalType":"address"},{"type":"uint256","name":"_tokenId","internalType":"uint256"}]},{"type":"function",
"stateMutability":"view","outputs":[{"type":"string","name":"","internalType":"string"}],"name":"standard","inputs":[]},{"type":"function","stateMutability":"view","outputs":[{"type":"string","name":"","internalType":"string"}],"name":"symbol","inputs":[]},{"type":"function","stateMutability":"nonpayable","outputs":[{"type":"bool","name":"","internalType":"bool"}],"name":"transfer","inputs":[{"type":"address","name":"_to","internalType":"address"},
{"type":"uint256","name":"_tokenId","internalType":"uint256"},{"type":"bytes","name":"_data","internalType":"bytes"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"transferOwnership","inputs":[{"type":"address","name":"newOwner","internalType":"address"}]},{"type":"function","stateMutability":"nonpayable","outputs":[],"name":"updateAuctionDuration","inputs":[{"type":"string","name":"_artwork_name","internalType":"string"},{"type":"uint256","name":"_index","internalType":"uint256"},
{"type":"uint256","name":"_new_duration_in_seconds","internalType":"uint256"}]},{"type":"function","stateMutability":"nonpayable","outputs":[{"type":"bool","name":"","internalType":"bool"}],"name":"withdrawBid","inputs":[{"type":"uint256","name":"_tokenId","internalType":"uint256"}]}]
        ,
        "0x7E7C9f515d06bAD40f8e1e7477421CF64Ca59E5D"
    );
}

export default contract;